services:
  db:
    container_name: baralho-de-bixo-db
    image: postgres:16
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: baralho-de-bixo-api
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src # Mount only source code for live reloading
      - ./package.json:/usr/src/app/package.json # Mount package.json
      - ./bun.lockb:/usr/src/app/bun.lockb # Mount lock file
      - node_modules:/usr/src/app/node_modules # Use named volume to preserve installed packages
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - NODE_ENV=${NODE_ENV}
      - TEST_MODE=${TEST_MODE}
    command: ["bun", "run", "dev"]

volumes:
  postgres_data:
  node_modules:
